### ISSUE TITLE
Bug is back: use snake_case for source file names on all ruby files 

### ISSUE THREAD

**Issue by Janther** [AtomLinter/linter-plus#92] opened 2015-06-24 13:23 UTC
The bug corresponding to this issue (https://github.com/AtomLinter/linter-rubocop/issues/2), that had been resolved in a previous version of linter is back.

**Comment by steelbrain** [comment] 2015-06-24 13:24
Dupe of https://github.com/AtomLinter/Linter/issues/585

**Closed by steelbrain** 2015-06-24 13:24 UTC
